on: push
name: Run tests on push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    steps:
      - name: "Clone and checkout branch"
        uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: "Install dependencies"
        run: yarn 
      - name: "Running tests"
        run: yarn test
